"""Agregar columnas stripe_payment_intent_id y stripe_client_secret

Revision ID: 44caa4ce6999
Revises: 
Create Date: 2025-03-30 16:08:54.594754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44caa4ce6999'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('stripe_client_secret', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.drop_column('transactions', 'blumonpay_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('blumonpay_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'stripe_client_secret')
    op.drop_column('transactions', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
